<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>pt.uninova</groupId>
  <version>0.1.0</version>
  <artifactId>ditag-tool</artifactId>
  <name>ditag-tool</name>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>23</maven.compiler.release>
  </properties>
  <build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.13.0</version>
		</plugin>
	</plugins>
  </build>
  <dependencies>
  	<dependency>
      <groupId>net.sourceforge.owlapi</groupId>
      <artifactId>owlapi-distribution</artifactId>
      <version>5.5.0</version>
  	</dependency>
    <dependency>
      <groupId>org.jdom</groupId>
      <artifactId>jdom2</artifactId>
      <version>2.0.6.1</version>
    </dependency>
	<!--Pellet support can be enabled by adding the corresponding dependency. Uncomment for Pellet--><!--<dependency>
	  <groupId>net.sourceforge.owlapi</groupId>
	  <artifactId>pellet-query-ignazio1977</artifactId>
	  <version>2.4.0-ignazio1977</version>
	</dependency>-->
	<dependency>
      <groupId>com.hp.hpl.jena</groupId>
	  <artifactId>jena</artifactId>
	  <version>2.6.4</version>
	  <exclusions>
		 <exclusion>
		  <groupId>org.slf4j</groupId>
		  <artifactId>slf4j-log4j12</artifactId>
	  	</exclusion>
	  </exclusions>
	</dependency>
	<dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.36</version>
    </dependency>
    <dependency>
      <groupId>jakarta.xml.bind</groupId>
      <artifactId>jakarta.xml.bind-api</artifactId>
      <version>4.0.1</version>
    </dependency>
      <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-xjc</artifactId>
      <version>4.0.4</version>
	</dependency>
	<dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>4.0.4</version>
	</dependency>
	<dependency>
      <groupId>net.sf.saxon</groupId>
      <artifactId>Saxon-HE</artifactId>
      <version>12.4</version>
    </dependency>
	<dependency>
	  <groupId>com.ethlo.json2xsd</groupId>
	  <artifactId>jsons2xsd</artifactId>
	  <version>2.1.0</version>
	</dependency>
	<dependency>
		<groupId>com.google.code.gson</groupId>
		<artifactId>gson</artifactId>
		<version>2.10.1</version>
	</dependency>
	<dependency>
      <groupId>com.ezylang</groupId>
      <artifactId>EvalEx</artifactId>
      <version>3.6.0</version>
    </dependency>
	<dependency>
	    <groupId>org.apache.commons</groupId>
	    <artifactId>commons-text</artifactId>
	    <version>1.14.0</version>
	</dependency>
	<dependency>
        <groupId>org.json</groupId>
        <artifactId>json</artifactId>
        <version>20240303</version>
    </dependency>
    <dependency>
	    <groupId>org.apache.ws.commons.schema</groupId>
	    <artifactId>XmlSchema</artifactId>
	    <version>1.4.7</version>
	</dependency>
	<dependency>
	    <groupId>jakarta.activation</groupId>
	    <artifactId>jakarta.activation-api</artifactId>
	    <version>2.1.3</version>
	</dependency>
	<dependency>
		<groupId>jakarta.json.bind</groupId>
		<artifactId>jakarta.json.bind-api</artifactId>
		<version>3.0.1</version>
	</dependency>
	<dependency>
	    <groupId>com.fasterxml.jackson.dataformat</groupId>
	    <artifactId>jackson-dataformat-csv</artifactId>
	    <version>2.17.0</version>
	</dependency>
	<dependency>
	    <groupId>com.opencsv</groupId>
	    <artifactId>opencsv</artifactId>
	    <version>5.8</version>
	</dependency>
	<dependency>
	    <groupId>io.github.liveontologies</groupId>
	    <artifactId>elk-owlapi</artifactId>
	    <version>0.6.0</version>
	</dependency>
  </dependencies>
</project>
